version: '3.8'

services:
  mongo:
    image: mongo:5.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  go-web-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-web-service
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017
    volumes:
      - .:/app

volumes:
  mongo-data:
    driver: local
